context.objects = [
  { factory = adapter
    args = {
        factory.name     = support.null-audio-sink
        node.name        = "mpcpi-clock"
        node.description = "MPC-Pi graph clock"
        media.class      = "Audio/Sink"
        audio.position   = [ FL FR ]
        audio.rate       = 44100
        priority.driver  = 5000
        priority.session = 2000
        node.group       = "mpcpi-audio"
        node.always-process = true
        monitor.channel-volumes = false
    }
  }
]
