monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.platform-soc_107c000000_sound.*" }
      { node.name = "~alsa_input.platform-soc_107c000000_sound.*" }
      { node.name = "~alsa_.*platform-1000480000.usb.*" }
    ]
    actions = { update-props = {
        node.group = "mpcpi-audio"
        priority.driver = 100
    } }
  }
]
