monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.platform-1000480000.usb.*" }
      { node.name = "~alsa_input.platform-1000480000.usb.*" }
    ]
    actions = {
      update-props = {
        api.alsa.disable-tsched = true
        api.alsa.period-size = 32
        api.alsa.period-num = 4
        api.alsa.headroom = 0
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
