-- Build the appliance's Ardour session from nothing.
--
-- Creates the whole desk the panel expects, so daw-ctl and the Maschine
-- UI find a session whose strip order matches the columns they draw:
--
--   1 MPC        the emulator's stereo out
--   2 GTR1  3 GTR2  4 MIC          input channels, each with its chain
--   5 GTR1+ 6 GTR2+ 7 MIC+         overdub partners for the layer pairs
--   8 AUX                          spare input / returns
--   + MPC1..MPC8                   the emulator's individual outs
--   + FX A (reverb), FX B (delay)  send buses
--
-- Strip order is load-bearing: OSC addresses strips by position, and the
-- panel draws column N as strip N. Creating them in this order is what
-- makes "one number means the same thing everywhere" true.
--
--   luasession session-template.lua      (env SESSION_DIR, SESSION_NAME)

local dir = os.getenv("SESSION_DIR") or "/tmp/mpc-daw"
local name = os.getenv("SESSION_NAME") or "mpcpi"
local rate = tonumber(os.getenv("SESSION_RATE") or "48000")
local results = {}

local function say(t) io.write(t .. "\n") io.flush() end
local function step(label, fn)
	local ok, err = pcall(fn)
	results[#results + 1] = string.format("%s: %s%s",
		ok and "PASS" or "FAIL", label, ok and "" or (" -- " .. tostring(err)))
	say(results[#results])
	return ok
end

local session
-- Try backends in order of how much they prove. On the appliance
-- PipeWire is up and JACK is the real path; over an ssh session on the
-- board there is no user sound server at all, and insisting on JACK made
-- create_session return nil - which reads as a broken template rather
-- than a missing daemon. Dummy still builds the whole desk and still
-- instantiates every plugin, which is what this template is asserting.
-- Backend selection and the route-group argument both differ by version
-- and by host; they live in one module so the plugin probe cannot drift
-- from this file. See scripts/daw/ardour-compat.lua for why each choice
-- is made the way it is.
local compat = dofile(os.getenv("MPCPI_COMPAT")
	or "scripts/daw/ardour-compat.lua")
local backend_used

step("select backend and create session", function()
	backend_used = compat.use_backend()
	session = create_session(dir, name, rate)
	assert(session, "create_session returned nil on " .. backend_used ..
		" (is the sound server running?)")
end)
say("backend: " .. tostring(backend_used))
assert(session, "cannot continue without a session")

-- Track creation: the 9-argument form (Ardour 9 added trigger_visibility).
local ROUTE_GROUP = compat.route_group()

local function add_audio(nm, ins)
	local tl = session:new_audio_track(ins, 2, ROUTE_GROUP, 1, nm,
		ARDOUR.PresentationInfo.max_order, ARDOUR.TrackMode.Normal, true, true)
	assert(tl:size() > 0, "no track created for " .. nm)
	return tl:front()
end

local tracks = {}
step("create channel strips", function()
	for _, nm in ipairs({ "MPC", "GTR1", "GTR2", "MIC",
	                      "GTR1+", "GTR2+", "MIC+", "AUX" }) do
		tracks[nm] = add_audio(nm, 2)
	end
end)

step("create individual-out tracks", function()
	-- The emulator exposes its eight individual outs as a separate node
	-- (MPC_OUTPUT_MODE=all); one mono track each so the MPC's drums can
	-- be mixed per voice group.
	for i = 1, 8 do
		tracks["MPC" .. i] = add_audio("MPC" .. i, 1)
	end
end)

step("create send buses", function()
	for _, nm in ipairs({ "FX A", "FX B" }) do
		local bl = session:new_audio_route(2, 2, ROUTE_GROUP, 1, nm,
			ARDOUR.PresentationInfo.Flag.AudioBus,
			ARDOUR.PresentationInfo.max_order)
		assert(bl:size() > 0, "no bus for " .. nm)
		tracks[nm] = bl:front()
	end
end)

local function add_plugin(route, uri, position)
	local p = ARDOUR.LuaAPI.new_plugin(session, uri, ARDOUR.PluginType.LV2, "")
	if not p or p:isnil() then
		return nil
	end
	route:add_processor_by_index(p, position or -1, nil, true)
	return p
end

-- Chains come from scripts/daw/chains.json, generated by chains.py, so
-- the Lua builder and the panel's FX page read the same definition and
-- cannot drift: the chips drawn on screen are literally this list.
local function read_chains(path)
	local f = io.open(path, "r")
	if not f then return nil end
	local text = f:read("*a")
	f:close()
	local out = {}
	for track, body in text:gmatch('"([^"]+)":%s*%[(.-)%]') do
		local slots = {}
		for obj in body:gmatch("{(.-)}") do
			local name = obj:match('"name":%s*"([^"]*)"')
			local uri = obj:match('"uri":%s*"([^"]*)"')
			local bypass = obj:match('"bypass":%s*true') ~= nil
			if uri and uri ~= "" then
				slots[#slots + 1] = { name = name, uri = uri,
				                      bypass = bypass }
			end
		end
		out[track] = slots
	end
	return out
end

local chain_path = os.getenv("CHAINS_JSON") or "scripts/daw/chains.json"
local chains = read_chains(chain_path)

step("insert chains from the manifest", function()
	assert(chains, "could not read " .. chain_path)
	local placed, skipped = 0, 0
	for track_name, slots in pairs(chains) do
		local route = tracks[track_name]
		if track_name == "MASTER" then
			route = session:master_out()
		end
		if route and not route:isnil() then
			for _, slot in ipairs(slots) do
				local p = add_plugin(route, slot.uri)
				if p then
					placed = placed + 1
					-- Bypassed slots are present but inactive: the
					-- player switches them in from the panel rather
					-- than waiting for a plugin to load mid-song.
					if slot.bypass then p:deactivate() end
				else
					skipped = skipped + 1
					say(string.format("  missing %s on %s", slot.uri,
						track_name))
				end
			end
		end
	end
	say(string.format("  placed %d plugins, %d unavailable", placed, skipped))
	assert(placed > 0, "no plugins placed at all")
end)

step("connect the emulator", function()
	-- MAME's native PipeWire node is named after the device tag, so the
	-- stereo out is ":speaker" and the individual outs ":outputs".
	local all = C.StringVector()
	AudioEngine:get_backend_ports("", ARDOUR.DataType("audio"),
		ARDOUR.PortFlags.IsOutput, all)
	local speaker, outs = {}, {}
	for i = 1, all:size() do
		local n = all:at(i - 1)
		if n:find("speaker") then speaker[#speaker + 1] = n end
		if n:find("outputs") then outs[#outs + 1] = n end
	end
	if #speaker >= 2 then
		for ch = 0, 1 do
			tracks["MPC"]:input():audio(ch):connect(speaker[ch + 1])
		end
	else
		say("  note: emulator not running, MPC input left unconnected")
	end
	for i = 1, math.min(8, #outs) do
		tracks["MPC" .. i]:input():audio(0):connect(outs[i])
	end
end)

step("save session", function()
	session:save_state("", false, false, false, false, false)
end)

print("TEMPLATE-SUMMARY-BEGIN")
for _, line in ipairs(results) do print(line) end
print("TEMPLATE-SUMMARY-END")

pcall(function()
	session:request_stop(false, false, ARDOUR.TransportRequestSource.TRS_UI)
end)
close_session()
